# Generated by Django 4.2.5 on 2023-10-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
