# Generated by Django 4.2.5 on 2023-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Milk', max_length=200),
        ),
    ]
