# Generated by Django 4.2.5 on 2023-10-14 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_shopaddress_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlist_model',
        ),
        migrations.DeleteModel(
            name='ShopAddress',
        ),
    ]
